module BitClust
  class Error < StandardError
    # 型エラー回避のため、nilの可能性を外した。
    def backtrace: () -> Array[String]
  end

  class RequestError < Error
  end

  class NotInTransaction < Error
  end

  class DocumentError < Error
  end

  class ScanError < DocumentError
  end

  class ParseError < DocumentError
  end

  class WrongInclude < DocumentError
  end

  class InvalidLink < DocumentError
  end

  class InvalidAncestor < DocumentError
  end

  class InvalidLibrary < DocumentError
  end

  class UserError < Error
  end

  class InvalidDatabase < UserError
  end

  class InvalidKey < UserError
  end

  class InvalidScheme < UserError
  end

  class NotFoundError < UserError
  end

  class LibraryNotFound < NotFoundError
  end

  class ClassNotFound < NotFoundError
  end

  class MethodNotFound < NotFoundError
  end

  class FunctionNotFound < NotFoundError
  end

  class DocNotFound < NotFoundError
  end

  module WriterError
    # 型エラー回避のため Exception#message の型をコピー
    def message: () -> String
  end

  class DocumentError
    include WriterError
  end

  class UserError
    include WriterError
  end
end
