module BitClust
  module Subcommands
    class ClassesCommand < Subcommand
      @rejects: untyped

      @verbose: untyped

      include CrossRubyUtils

      def initialize: () -> void

      def parse: (untyped argv) -> untyped

      def exec: (untyped argv, untyped options) -> untyped

      def defined_classes: (untyped ruby, untyped lib, untyped rejects) -> untyped
    end
  end
end
