module BitClust
  module Subcommands
    class EPUBCommand < Subcommand
      @verbose: untyped

      @catalogdir: untyped

      @templatedir: untyped

      @themedir: untyped

      @filename: untyped

      @keep: untyped

      def initialize: () -> void

      def exec: (untyped argv, untyped options) -> untyped
    end
  end
end
