module BitClust
  module Subcommands
    class ExtractCommand < Subcommand
      def initialize: () -> void

      def exec: (untyped argv, untyped options) -> untyped

      def show_library: (untyped lib) -> untyped
    end
  end
end
