module BitClust
  module Subcommands
    class HtmlfileCommand < Subcommand
      @target: untyped

      @templatedir: untyped

      @baseurl: untyped

      @version: untyped

      @capi: untyped

      @rd_file: untyped

      def initialize: () -> void

      def exec: (untyped argv, untyped options) -> (nil | untyped)

      private

      def lookup: (untyped lib, untyped key) -> untyped
    end
  end
end
