module BitClust
  module Subcommands
    class PropertyCommand < Subcommand
      @mode: untyped

      def initialize: () -> void

      def parse: (untyped argv) -> untyped

      def exec: (untyped argv, untyped options) -> untyped
    end
  end
end
