module BitClust
  module Subcommands
    class UpdateCommand < Subcommand
      @root: untyped

      @library: untyped

      def initialize: () -> void

      def parse: (untyped argv) -> untyped

      def exec: (untyped argv, untyped options) -> untyped

      private

      def guess_library_name: (untyped path) -> untyped

      def get_c_filename: (untyped path) -> untyped
    end
  end
end
