module BitClust
  # Provides completion search methods like _search_classes, _search_methods. 
  # Included by MethodDatabase and FunctionDatabase.
  module Completion
    @ts: untyped

    @intern_table: untyped

    @classnametable: untyped

    @method_index_small: untyped

    @method_names: untyped

    @method_index: untyped

    @method_index_0: untyped

    private

    def _search_classes: (untyped pattern) -> untyped

    def _search_methods: (untyped pattern) -> untyped

    def _search_functions: (untyped pattern) -> untyped

    def search_svar: (untyped c, untyped pattern) -> untyped

    def search_methods_from_cname: (untyped pattern) -> untyped

    def mspec_from_cref_mname: (untyped cref, untyped name) -> untyped

    def search_methods_from_mname: (untyped pattern) -> untyped

    def search_methods_from_cname_mname: (untyped pattern) -> untyped

    def expand_method_name: (untyped c, untyped ts, untyped m) -> (::Array[untyped] | untyped)

    def timer_init: () -> untyped

    def split_time: (untyped msg) -> untyped

    def count_class: (untyped recs) -> untyped

    def make_cm_combination: (untyped cpat, untyped ts, untyped mnames) -> untyped

    def try: (untyped candidates) { (untyped) -> untyped } -> (untyped | ::Array[untyped])

    def typechars: (untyped type, untyped mpattern) -> (::Array[untyped] | ::Array[":" | ".#"] | ::Array[".#" | ":"])

    def unify_entries: (untyped ents) -> untyped

    # Case-insensitive search.  Optimized for constant search.
    def expand_ic: (untyped xs, untyped pattern) -> (::Array[untyped] | untyped)

    def expand: (untyped xs, untyped pattern) -> (::Array[untyped] | untyped)

    # list up all matched items (without squeezing)
    def expand_name_wide: (untyped names, untyped pattern) -> untyped

    # list up matched items (with squeezing)
    def expand_name_narrow: (untyped names, untyped pattern, ?untyped? suffixes) -> (::Array[untyped] | untyped)

    # squeeze result of #expand_name_wide
    def squeeze_names: (untyped result1, untyped pattern, ?untyped? suffixes) -> untyped

    def suffix_pattern: (untyped suffixes) -> ("" | ::String)

    def save_completion_index: () -> untyped

    def intern_classname: (untyped name) -> untyped

    def intern_table: () -> untyped

    def save_class_index: () -> untyped

    def classnametable: () -> untyped

    def save_method_index_narrow: () -> untyped

    def method_index_small: () -> untyped

    # canonical class name, no inheritance
    def mname2crefs_narrow: (untyped name) -> untyped

    def save_method_index: () -> untyped

    def method_names: () -> untyped

    # includes class aliases, includes inherited methods
    def mname2crefs_wide: (untyped name) -> untyped

    def mname2crefs_0: (untyped name) -> (untyped | nil)

    def method_index_0: () -> untyped
  end

  # Represents result of completion search.
  # Has many SearchResult::Record.
  class SearchResult
    @database: untyped

    @pattern: untyped

    @classes: untyped

    @records: untyped

    def self.empty: (untyped db, untyped pattern) -> untyped

    def initialize: (untyped db, untyped pattern, untyped classes, untyped records) -> void

    attr_reader database: untyped

    attr_reader pattern: untyped

    attr_reader classes: untyped

    attr_reader records: untyped

    def inspect: () -> ::String

    def fail?: () -> untyped

    def success?: () -> untyped

    def determined?: () -> untyped

    def name: () -> untyped

    def names: () -> untyped

    def record: () -> untyped

    def each_record: () { (?) -> untyped } -> untyped

    # Wraps an Entry.
    class Record
      @db: untyped

      @specs: untyped

      @origin: untyped

      @entry: untyped

      @hash: untyped

      def initialize: (untyped db, untyped spec, ?untyped? origin, ?untyped? entry) -> void

      attr_writer db: untyped

      attr_reader specs: untyped

      def origin: () -> untyped

      def idstring: () -> untyped

      def entry: () -> untyped

      def name: () -> untyped

      def names: () -> untyped

      def class_name: () -> untyped

      def method_name: () -> untyped

      def original_name: () -> untyped

      def ==: (untyped other) -> (false | untyped)

      alias eql? ==

      def hash: () -> untyped

      def <=>: (untyped other) -> untyped

      def merge: (untyped other) -> untyped

      def owned_method?: () -> untyped

      def method_of_alias_class?: () -> untyped

      def inherited_method?: () -> untyped
    end
  end
end
