module BitClust
  # Abstract class for BitClust DB.
  # Each entry is written in a file.
  #
  # Has subclass MethodDatabase (Ruby stuff) and FunctionDatabase (C stuff).
  class Database
    private

    public

    private
  end
end
