module BitClust
  # Parser for C API reference file (refm/capi/src/*)
  # Much simpler than Ruby API reference parser(RRDParser)
  # because C APIs does not have library, class, etc.
  class FunctionReferenceParser
    @db: untyped

    @filename: untyped

    @path: untyped

    # Returns an array of FunctionEntry
    def self.parse_file: (untyped path, ?::Hash[untyped, untyped] params) -> untyped

    def initialize: (untyped db) -> void

    def parse_file: (untyped path, untyped filename, untyped properties) -> untyped

    def parse: (untyped f, untyped filename, ?::Hash[untyped, untyped] params) -> untyped

    private

    def file_entries: (untyped f) -> untyped

    def entry: (untyped header, untyped body) -> untyped

    def parse_header: (untyped header) -> untyped
  end

  # Represents C function signature
  # (Used internally in this file)
  FunctionHeader: untyped
end
