module BitClust
  # Utility functions for HTML tag generation
  module HTMLUtils
    include NameUtils

    private

    # make method anchor from MethodEntry
    def link_to_method: (untyped m, ?bool specp) -> untyped

    def library_link: (untyped name, ?untyped? label, ?untyped? frag) -> untyped

    def class_link: (untyped name, ?untyped? label, ?untyped? frag) -> untyped

    def method_link: (untyped spec, ?untyped? label, ?untyped? frag) -> untyped

    def method_url: (untyped spec, ?untyped? frag) -> untyped

    def function_link: (untyped name, ?untyped? label, ?untyped? frag) -> untyped

    def document_link: (untyped name, ?untyped? label, ?untyped? frag) -> untyped

    def fragment: (untyped str) -> (untyped | "")

    def a_href: (untyped url, untyped label) -> ::String

    ESC: ::Hash[::String, "&amp;" | "&quot;" | "&lt;" | "&gt;"]

    def escape_html: (untyped str) -> untyped

    ESCrev: untyped

    def unescape_html: (untyped str) -> untyped
  end
end
