module BitClust
  # Represents infomation to identify a method (library, class/module,
  # type and name.)
  #
  # A MethodID has #library, #klass, #typename, and method name.
  # #library, #klass, #typename must be an object.
  class MethodID
    def inspect: () -> ::String

    alias typename type
  end

  # A MethodSpec has #klass, #type, #method and #library.
  # All attributes are string.
  # #library is optional.
  class MethodSpec
    def inspect: () -> ::String

    def to_s: () -> ::String

    alias eql? ==
  end

  # A MethodNamePattern has #klass, #type, #method and #library.
  # All attributes are string.
  # All attributes are optional.
  class MethodNamePattern
    def inspect: () -> ::String

    private

    public
  end
end
