module BitClust
  # Database for Ruby entries (library, class, method).
  class MethodDatabase < Database
    private

    public

    private

    public

    private

    public

    private

    public

    private

    public

    private

    public
  end
end
