module BitClust
  # Represents detailed signature of a method in a class/module.
  # Includes parameters, block specification and return type.
  class MethodSignature
    include NameUtils

    METHOD_SIGNATURE_RE: ::Regexp

    def self.parse: (untyped line) -> untyped

    def initialize: (untyped name, untyped params, untyped block, untyped type) -> void

    attr_reader name: untyped

    attr_reader params: untyped

    attr_reader block: untyped

    attr_reader type: untyped

    def to_s: () -> untyped

    def friendly_string: () -> untyped

    def inspect: () -> ::String
  end
end
