module BitClust
  # Entry for methods(instance methods/singleton methods/module_functions),
  # constants and special variables(like $!).
  class MethodEntry < Entry
    alias eql? ==

    def inspect: () -> ::String

    def label: () -> ::String

    def short_label: () -> ::String
  end
end
