module BitClust
  # Utilities for conversion among names, ids and URL fragments.
  module NameUtils
    LIBNAME_RE: ::Regexp

    CONST_RE: ::Regexp

    CONST_PATH_RE: ::Regexp

    CLASS_NAME_RE: ::Regexp

    CLASS_PATH_RE: ::Regexp

    METHOD_NAME_RE: ::Regexp

    TYPEMARK_RE: ::Regexp

    METHOD_SPEC_RE: ::Regexp

    GVAR_RE: ::Regexp

    MID: ::Regexp

    @@split_method_id: untyped
  end
end
