module BitClust
  # Superclass of Preprocessor
  class LineFilter
    include ParseUtils
  end

  # Handle pragmas like #@todo, #@include, #@since, etc.
  class Preprocessor < LineFilter
    def initialize: (untyped f, ?::Hash[untyped, untyped] params) -> void

    private
  end

  # Used by tools/stattodo.rb
  class LineCollector < LineFilter
    def self.process: (untyped path) -> untyped

    def self.wrap: (untyped f) -> untyped

    private

    def next_line: (untyped f) -> untyped
  end
end
