module BitClust
  # Compiles doc into HTML.
  class RDCompiler
    @urlmapper: untyped

    @catalog: untyped

    @hlevel: untyped

    @type: untyped

    @library: untyped

    @class: untyped

    @method: untyped

    @option: untyped

    @opt: untyped

    @f: untyped

    @out: untyped

    @item_stack: untyped

    include HTMLUtils

    include TextUtils

    include Translatable

    def initialize: (untyped urlmapper, ?::Integer hlevel, ?::Hash[untyped, untyped] opt) -> void

    def compile: (untyped src) -> untyped

    def compile_function: (untyped f, ?untyped? opt) -> untyped

    # FIXME
    def compile_method: (untyped m, ?untyped? opt) -> untyped

    private

    def setup: (untyped src, ?untyped? entry) { () -> untyped } -> untyped

    def library_file: () -> untyped

    def entry: () -> untyped

    def entry_chunk: () -> untyped

    def headline: (untyped line) -> untyped

    def h: (untyped level, untyped label, ?untyped? frag) -> ::String

    ITEM_RE: ::Regexp

    def item_list: (?::Integer level) -> untyped

    def dlist: () -> untyped

    # empty lines separate paragraphs.
    def dd_with_p: () -> untyped

    # empty lines do not separate paragraphs.
    def dd_without_p: () -> untyped

    def dt: (untyped s) -> ::String

    def stop_on_syntax_error?: () -> (true | untyped)

    def emlist: () -> untyped

    def list: () -> untyped

    def canonicalize: (untyped lines) -> untyped

    def paragraph: () -> untyped

    def read_paragraph: (untyped f) -> untyped

    def see: () -> untyped

    def todo: () -> untyped

    def entry_info: () -> untyped

    # FIXME: parse @param, @return, ...
    def entry_paragraph: () -> untyped

    def read_entry_paragraph: (untyped f) -> untyped

    def method_signature: (untyped sig_line, untyped first) -> untyped

    BracketLink: ::Regexp

    NeedESC: ::Regexp

    def compile_text: (untyped str) -> untyped

    def bracket_link: (untyped link, ?untyped? label, ?untyped? frag) -> untyped

    def protect: (untyped src) { () -> untyped } -> untyped

    def direct_url: (untyped url) -> ::String

    def reference_link: (untyped arg) -> untyped

    BLADE_URL: "https://blade.ruby-lang.org/%s/%s"

    def blade_link: (untyped ml, untyped num) -> ::String

    RFC_URL: "https://tools.ietf.org/html/rfc%s"

    def rfc_link: (untyped num) -> ::String

    MAN_CMD_URL: ::String

    MAN_FCN_URL: ::String

    MAN_HEADER_URL: ::String

    MAN_LINUX_URL: "http://man7.org/linux/man-pages/man%1$s/%2$s.%1$s.html"

    MAN_FREEBSD_URL: "http://www.freebsd.org/cgi/man.cgi?query=%2$s&sektion=%1$s&manpath=FreeBSD+9.0-RELEASE"

    def man_url: (untyped section, untyped page) -> untyped

    def man_link: (untyped spec) -> (untyped | ::String)

    BUGS_URL: "https://bugs.ruby-lang.org/issues/%s"

    def bugs_link: (untyped type, untyped id) -> ::String

    def rdoc_url: (untyped method_id, untyped version) -> ::String

    def rdoc_link: (untyped method_id, untyped version) -> untyped

    def complete_spec: (untyped spec0) -> untyped

    def seems_code: (untyped text) -> untyped

    def string: (untyped str) -> untyped

    def line: (untyped str) -> untyped

    def nl: () -> untyped

    def text_node_from_lines: (untyped lines) -> untyped
  end
end
