module BitClust
  # Actions of BitClust server.
  class RequestHandler
    def initialize: (untyped db, untyped manager) -> void

    def handle: (untyped webrick_req) -> untyped

    private

    def _handle: (untyped req) -> untyped

    def error_response: (untyped err) -> untyped

    def not_found_response: (untyped err) -> untyped

    def handle_library: (untyped req) -> untyped

    def handle_class: (untyped req) -> untyped

    def handle_method: (untyped req) -> untyped

    def library_index: () -> untyped

    def class_index: () -> untyped

    def handle_opensearchdescription: (untyped req) -> untyped

    def handle_search: (untyped req) -> untyped

    def handle_doc: (untyped req) -> untyped

    def handle_function: (untyped req) -> untyped

    def function_index: () -> untyped
  end

  class RackRequestHandler < RequestHandler
    def handle: (untyped rack_req) -> untyped
  end

  class Request
    include NameUtils

    def initialize: (untyped wreq) -> void

    def library?: () -> untyped

    def class?: () -> untyped

    def method?: () -> untyped

    def doc_name: () -> untyped

    def library_name: () -> (nil | untyped)

    def class_name: () -> (nil | untyped)

    def method_spec: () -> (nil | untyped)

    def defined_type?: () -> untyped

    def type_id: () -> untyped

    def function?: () -> untyped

    def function_name: () -> (nil | untyped)

    def ancestors_level: () -> untyped

    def query: () -> untyped

    def full_uri: () -> untyped

    private

    def type_param: () -> (nil | untyped)

    def parse_path_info: () -> (nil | untyped)

    def path_info: () -> untyped
  end

  class RackRequest < Request
    def initialize: (untyped rack_req) -> void

    def query: () -> untyped

    def path_info: () -> untyped

    def full_uri: () -> untyped
  end

  class Screen
    def response: () -> untyped
  end

  class Response
    def initialize: (untyped screen) -> void

    def update: (untyped webrick_res) -> untyped

    def rack_finish: () -> ::Array[untyped | ::Hash[::String, untyped] | ::Array[untyped]]
  end
end
