module BitClust
  # Parser for Ruby API reference file (refm/api/src/*)
  class RRDParser
    SIGNATURE: ::Regexp

    GVAR: ::Regexp

    class Context
      include NameUtils
    end

    class Chunk
      def inspect: () -> ::String
    end

    class Signature
      include NameUtils

      def inspect: () -> ::String

      def to_s: () -> ::String
    end
    include NameUtils

    include ParseUtils
  end
end
