module BitClust
  class Database
    include DRb::DRbUndumped
  end

  class Entry
    include DRb::DRbUndumped
  end

  class SearchResult
    include DRb::DRbUndumped
  end
end

class Object
  def _remote_object?: () -> false
end

class DRb::DRbObject
  def _remote_object?: () -> true
end
