module BitClust
  # Tiny search engine for BitClust server.
  # Note: loads all the entries onto memory, so first search will be slow.
  module SimpleSearcher
    include NameUtils

    def self?.search_pattern: (untyped db, untyped pat) -> (::Array[untyped] | untyped)

    def self?.find_class: (untyped db, untyped cname) -> untyped

    def self?.find_class_method: (untyped db, untyped cname, untyped type, untyped mname) -> untyped

    def self?.find_methods: (untyped db, untyped mname) -> untyped

    def self?.find_special_vars: (untyped db, untyped mname) -> untyped

    def self?.to_pattern: (untyped pat) -> untyped

    def self?.parse_method_spec_pattern: (untyped pat) -> (untyped | ::Array[untyped | nil] | ::Array[nil | "$" | untyped] | ::Array[untyped])

    def self?.parse_method_spec_pattern0: (untyped q) -> ::Array[untyped | nil]
  end
end
