module BitClust
  # Base class for bitclust subcommands.
  class Subcommand
    def initialize: () -> void

    def parse: (untyped argv) -> untyped

    def help: () -> untyped

    def exec: (untyped argv, untyped options) -> untyped
  end
end
