module BitClust
  class SyntaxHighlighter < Ripper::Filter
    class Error < StandardError
      def message: () -> ::String
    end

    class ParseError < Error
    end

    class CompileError < Error
    end

    LABELS: ::Hash[untyped, untyped]

    KEYWORDS: ::Array["BEGIN" | "END" | "alias" | "begin" | "break" | "case" | "defined\\?" | "do" | "else" | "elsif" | "end" | "ensure" | "for" | "if" | "in" | "next" | "redo" | "rescue" | "raise" | "retry" | "return" | "super" | "then" | "undef" | "unless" | "until" | "when" | "while" | "yield"]

    KEYWORDS_PSEUDO: ::Array["loop" | "include" | "extend" | "raise" | "alias_method" | "attr" | "catch" | "throw" | "private" | "module_function" | "public" | "protected" | "true" | "false" | "nil" | "__FILE__" | "__LINE__"]

    BUILTINS_Q: ::Array["autoload" | "block_given" | "const_defined" | "eql" | "equal" | "frozen" | "include" | "instance_of" | "is_a" | "iterator" | "kind_of" | "method_defined" | "nil" | "private_method_defined" | "protected_method_defined" | "public_method_defined" | "respond_to" | "tainted"]

    BUILTINS_B: ::Array["chomp" | "chop" | "exit" | "gsub" | "sub"]
    include BitClust::HTMLUtils
  end
end
