module BitClust
  # Utility for tweaking text.
  module TextUtils
    def self?.detab: (untyped str, ?::Integer ts) -> untyped

    def self?.unindent_block: (untyped lines) -> untyped

    def self?.n_minimum_indent: (untyped lines) -> untyped

    def self?.n_indent: (untyped line) -> untyped

    INDENT_RE: { 2 => ::Regexp, 4 => ::Regexp, 8 => ::Regexp }

    def self?.unindent: (untyped line, untyped n) -> untyped
  end
end
