module BitClust
  module Subcommands
    class EPUBCommand < Subcommand
      @verbose: bool

      @catalogdir: Pathname?

      @templatedir: Pathname

      @themedir: Pathname

      @filename: String

      @keep: bool

      @outputdir: Pathname

      @fs_casesensitive: true?

      def initialize: () -> void

      def exec: (Array[String] argv, Hash[Symbol, untyped] options) -> void
    end
  end
end
