module BitClust
  module Subcommands
    class InitCommand < Subcommand
      def initialize: () -> void

      STANDARD_PROPERTIES: Array[String]

      def exec: (Array[String] argv, Hash[Symbol, untyped] options) -> void
    end
  end
end
