module BitClust
  module Subcommands
    class ListCommand < Subcommand
      @mode: (nil | :library | :class | :method | :function)

      def initialize: () -> void

      def parse: (Array[String] argv) -> void

      def exec: (Array[String] argv, Hash[Symbol, String?] options) -> void
    end
  end
end
