module BitClust
  module Subcommands
    class MethodsCommand < Subcommand
      @requires: Array[String]

      @verbose: bool

      @version: String

      @mode: (:list | :diff)

      @target: String

      @content: bool

      @ri_path: String

      include CrossRubyUtils

      def initialize: () -> void

      def parse: (Array[String] argv) -> void

      def exec: (Array[String] argv, Hash[Symbol, untyped] options) -> void

      def expand_mf: (String n) -> ([String, String] | String)

      def crossrubyutils_sort_entries: (Array[String] ents) -> Array[String]

      ORDER: Hash[String, Integer]

      def m_order: (String m) -> [Integer, String]

      def defined_methods: (String ruby, String classname) -> Array[String]
    end
  end
end
