module BitClust
  module Subcommands
    class PreprocCommand < Subcommand
      @params: Hash[untyped, untyped]

      def initialize: () -> void

      def exec: (Subcommand::argv argv, Subcommand::options options) -> void
    end
  end
end
