module BitClust
  module Subcommands
    class QueryCommand < Subcommand
      def initialize: () -> void

      def exec: (Array[String] argv, Hash[Symbol, String?] options) -> void
    end
  end
end
