module BitClust
  # Main class of BitClust server application.
  # Actual actions are implemneted by RequestHandler.
  #
  # Supports Rack and WEBrick.
  class App
    @options: untyped

    @interfaces: untyped

    @versions: untyped

    # Redirect from '/' to "#{viewpath}/"
    @index: untyped

    def initialize: (Hash[Symbol, untyped] options) -> void

    attr_reader interfaces: untyped

    attr_reader versions: untyped

    def index: (untyped req) -> untyped

    def get_instance: (WEBrick::HTTPServer server, *untyped) -> self

    def service: (WEBrick::HTTPRequest req, WEBrick::HTTPResponse res) -> void

    def call: (untyped env) -> ::Array[200 | { "Content-Type" => "text/html; charset=utf-8" } | ::Array[untyped]]
  end
end
