module BitClust
  class Entry
    include NameUtils

    interface _PersistentProperties
      def init_properties: () -> void
      def clear: () -> void
      def _set_properties: (Hash[String, String] h) -> void
      def _get_properties: () -> Hash[String, String]
      def unload: () -> void
    end
    include BitClust::Entry::_PersistentProperties
    def self.persistent_properties: () { () -> void } -> void
    def self.property: (Symbol name, Property::property_type type) -> void
    self.@slots: Array[Property]

    class Property
      type property_type = 'String' | 'Symbol' | 'bool' | 'LibraryEntry' | 'ClassEntry' | 'MethodEntry' | '[String]' | '[LibraryEntry]' | '[ClassEntry]'  | '[MethodEntry]' | 'Location' | ''
      def initialize: (Symbol name, property_type type) -> void
      attr_reader name: Symbol
      @type: property_type

      def initial_value: () -> String
      def deserializer: () -> String
      def serializer: () -> String
    end

    alias self.load self.new

    def initialize: ((MethodDatabase | FunctionDatabase) db) -> void

    # FunctionEntry では FunctionDatabase
    @db: MethodDatabase

    # サブクラスで定義されている
    attr_reader id: String

    # サブクラスで定義されている
    def name: () -> String

    # サブクラスで定義されている
    def self.type_id: () -> Symbol

    def type_id: () -> Symbol

    # for entry_class.type_id
    interface _TypeId
      def type_id: () -> Symbol
    end

    @loaded: bool
    def loaded?: () -> bool

    def encoding: () -> String

    # サブクラスで定義されている
    def source: () -> String

    def synopsis_source: () -> String

    def detail_source: () -> String

    def save: () -> void

    private

    def load: () -> void

    def saved?: () -> bool

    def restore_library: (String id) -> LibraryEntry

    def restore_class: (String id) -> (nil | ClassEntry)

    def restore_libraries: (String str) -> Array[LibraryEntry]

    def restore_classes: (String str) -> Array[ClassEntry]

    def restore_methods: (String str) -> Array[MethodEntry]

    interface _LoadableClass[T]
      def load: (MethodDatabase, String) -> T
    end
    # klass < Entry, Array[klass]
    def restore_entries: [S < _LoadableClass[T], T < Entry](String? str, S klass) -> Array[T]

    def serialize_entry: (Entry? x) -> String

    def serialize_entries: (Array[Entry] xs) -> String

    def objpath: () -> ::String

    def path_string: (Array[String] path) -> String
  end
end
