module BitClust
  class FunctionEntry < Entry
    def self.type_id: () -> :function

    def initialize: (untyped db, untyped id) -> void
    attr_reader id: untyped

    def inspect: () -> String
    def name_match?: (Regexp re) -> Integer?
    def <=>: (FunctionEntry other) -> Integer?

    attr_accessor filename: String
    attr_accessor macro: bool
    attr_accessor private: bool
    attr_accessor type: String
    attr_accessor name: String
    attr_accessor params: String
    attr_accessor source: String
    attr_accessor source_location: Location

    alias label id
    alias macro? macro
    alias private? private

    def public?: () -> bool
    def callable?: () -> bool

    def type_label: () -> ("macro" | "function")
    alias kind type_label

    def header: () -> String

    def description: () -> String
  end
end
