module BitClust
  # Web server interface for BitClust server
  class Interface
    @webrick_conf: Hash[untyped, untyped]

    @handler: ::BitClust::RackRequestHandler

    $bitclust_context_cache: ::BitClust::RackRequestHandler?

    def initialize: (?::Hash[untyped, untyped] webrick_conf) { () -> (::BitClust::RackRequestHandler | ::BitClust::RequestHandler) } -> void

    # for WEBrick servlet
    def get_instance: (WEBrick::HTTPServer server) -> WEBrickServlet

    def main: () -> void

    # for rack
    def call: (Rack::env env) -> Rack::response

    private

    def fastcgi?: () -> bool?

    def mod_ruby?: () -> false

    class CGI < ::WEBrick::CGI
      @handler: untyped

      def main: (untyped handler) -> untyped

      def do_GET: (untyped wreq, untyped wres) -> untyped

      alias do_POST do_GET
    end

    class FCGI < CGI
      @handler: untyped

      def main: (untyped handler) -> untyped
    end

    class WEBrickServlet < ::WEBrick::HTTPServlet::AbstractServlet
      def do_GET: (untyped wreq, untyped wres) -> untyped

      alias do_POST do_GET
    end
  end
end
