class String
  attr_accessor location: ::BitClust::Location
end

module BitClust
  class LineStream
    def initialize: (_Gets | StringIO f) -> void
    @f: _Gets

    def gets: () -> String?

    # _Gets 用
    def path: () -> String?
    def lineno: () -> Integer
  end

  class Location
    def initialize: (String? file, Integer line) -> void
                  | (Pathname file, Integer line) -> void

    attr_reader file: (String? | Pathname)

    attr_reader line: Integer

    def to_s: () -> String

    def inspect: () -> String
  end

  module ParseUtils
    def parse_error: (String msg, String line) -> bot
  end
end
