module BitClust
  class LineFilter
    include ParseUtils
    include Enumerable[String]

    def initialize: (_Gets f) -> void

    @f: _Gets
    @buf: Array[String]

    def gets: () -> String?

    def each: () { (String) -> void } -> void

    # abstract
    def next_line: (_Gets) -> String?

    # _Gets 用
    def lineno: () -> Integer
  end

  class Preprocessor < LineFilter
    @params: Database::database_properties
    @last_if: String?
    @state_stack: Array[State]

    def initialize: (_Gets f, ?Database::database_properties params) -> void

    def self.read: (File | String path, ?Database::database_properties params) -> String

    def self.process: (string | _ToPath path, ?Database::database_properties params) -> Array[String]

    def self.wrap: (File | StringIO f, ?Database::database_properties params) -> instance

    def path: () -> String?

    def next_line: (_Gets) -> String?

    def cond_stmt_begin: (String line, String cond) -> void

    def build_cond_by_value: (String line, String left) -> String

    def current_cond: () -> State

    def cond_init: () -> void

    def cond_toplevel?: () -> bool

    def cond_push: (bool bool) -> void

    def cond_invert: () -> void

    def cond_pop: () -> void

    type evaluated_result = String | Integer | nil

    def eval_cond: (String str) -> bool

    def eval_expr: (StringScanner s) -> evaluated_result

    def eval_expr_p: (StringScanner s) -> evaluated_result

    def read_conj: (StringScanner s) -> String?

    def read_op: (StringScanner s) -> String?

    def eval_primary: (StringScanner s) -> evaluated_result

    def samplecode_begin: (String line, String description) -> void

    def samplecode_end: () -> void

    def samplecode_push: (String description) -> void

    def samplecode_pop: () -> void

    def samplecode_processing?: () -> bool

    def samplecode_description_by_value: (String line) -> String

    def scan_error: (String msg) -> bot

    class State
      type state_label = :toplevel | :samplecode | :condition
      attr_reader current: Symbol
      @is_processing: bool
      @label: state_label

      def initialize: (bool is_processing, state_label label) -> void

      def next: (bool is_processing, state_label label) -> State

      def toplevel?: () -> bool

      def processing?: () -> bool

      def samplecode?: () -> bool
    end
  end

  class LineCollector < LineFilter
    def self.process: (String path) -> Array[String]

    def self.wrap: (File f) -> instance

    private

    def next_line: (_Gets f) -> String?
  end
end
