module BitClust
  class ScreenManager
    @conf: Hash[Symbol, untyped]

    def initialize: (Hash[Symbol, untyped] h) -> void

    private

    def default_message_catalog: (Hash[Symbol, untyped] h) -> MessageCatalog

    public

    def entry_screen: (Entry | Array[Entry] entry, Hash[Symbol, untyped] opt) -> Screen

    def library_index_screen: (untyped libs, untyped opt) -> LibraryIndexScreen

    def library_screen: (untyped lib, untyped opt) -> LibraryScreen

    def class_index_screen: (untyped cs, untyped opt) -> ClassIndexScreen

    def class_screen: (untyped c, untyped opt) -> ClassScreen

    def method_screen: (untyped ms, untyped opt) -> MethodScreen

    def opensearchdescription_screen: (untyped request_full_uri, untyped opt) -> OpenSearchDescriptionScreen

    def search_screen: (untyped result, untyped opt) -> SearchScreen

    def doc_screen: (untyped d, untyped opt) -> DocScreen

    def function_screen: (untyped f, untyped opt) -> FunctionScreen

    def function_index_screen: (untyped fs, untyped opt) -> FunctionIndexScreen

    private

    def new_screen: (singleton(LibraryIndexScreen) c, *untyped args) -> LibraryIndexScreen
                  | (singleton(LibraryScreen) c, *untyped args) -> LibraryScreen
                  | (singleton(ClassIndexScreen) c, *untyped args) -> ClassIndexScreen
                  | (singleton(ClassScreen) c, *untyped args) -> ClassScreen
                  | (singleton(MethodScreen) c, *untyped args) -> MethodScreen
                  | (singleton(OpenSearchDescriptionScreen) c, *untyped args) -> OpenSearchDescriptionScreen
                  | (singleton(SearchScreen) c, *untyped args) -> SearchScreen
                  | (singleton(DocScreen) c, *untyped args) -> DocScreen
                  | (singleton(FunctionScreen) c, *untyped args) -> FunctionScreen
                  | (singleton(FunctionIndexScreen) c, *untyped args) -> FunctionIndexScreen
                  | (untyped c, *untyped args) -> untyped
  end

  class URLMapper

    @css_url: String

    @favicon_url: String

    @theme: String

    include NameUtils

    def initialize: (Hash[Symbol, String?] h) -> void

    attr_reader base_url: String

    attr_reader cgi_url: String

    def css_url: () -> ::String

    def custom_css_url: (String css) -> ::String

    def js_url: () -> ::String

    def custom_js_url: (String js) -> ::String

    def favicon_url: () -> ::String

    def library_index_url: () -> ::String

    def library_url: (String name) -> ::String

    def class_url: (String name) -> ::String

    def method_url: (String spec) -> ::String

    def function_index_url: () -> ::String

    def function_url: (String name) -> ::String

    def opensearchdescription_url: () -> ::String

    def search_url: () -> ::String

    def spec_url: (String name) -> ::String

    def document_url: (String name) -> ::String

    def canonical_url: (String current_url) -> String
  end

  class TemplateRepository
    @prefix: String

    def initialize: (String prefix) -> void

    def load: (String id) -> String

    private

    def preproc: (String template) -> String
  end

  class Screen
    def self.for_entry: (Entry | Array[Entry] entry) -> singleton(Screen)

    def status: () -> nil

    # TemplateScreen 以外にはある。
    def body: () -> String
  end

  class ErrorScreen < Screen
    @error: Exception

    include HTMLUtils

    def initialize: (Exception err) -> void

    def status: () -> 500

    def content_type: () -> String

    def body: () -> ::String
  end

  class NotFoundScreen < Screen
    @error: untyped

    include HTMLUtils

    def initialize: (untyped err) -> void

    def status: () -> 404

    def content_type: () -> String

    def body: () -> ::String
  end

  class TemplateScreen < Screen
    @urlmapper: URLMapper

    @template_repository: TemplateRepository

    @default_encoding: String

    @target_version: String

    @conf: Hash[Symbol, untyped]

    @hlevel: Integer

    include Translatable

    include HTMLUtils

    # この階層では定義されていないので undef の代わりに bot にしておく。
    def body: () -> bot

    def initialize: (Hash[Symbol, untyped] h) -> void

    def content_type: () -> String

    def encoding: () -> String

    def ruby_version: () -> String

    def google_tag_manager: () -> String

    def meta_robots: () -> String

    def meta_description: () -> String

    private

    def default_encoding: () -> String

    def run_template: (String id, ?bool layout) -> String

    # erb.def_method(self.class, 'layout', 'layout.erb')
    def layout: () { () -> untyped } -> String

    def h: (_ToS str) -> String

    def css_url: () -> String

    def custom_css_url: (String css) -> String

    def js_url: () -> String

    def custom_js_url: (String js) -> String

    def favicon_url: () -> String

    def current_url: () -> bot

    def canonical_url: () -> String

    def edit_url: (Location location) -> String

    def opensearchdescription_url: () -> String

    def search_url: () -> String

    def library_index_url: () -> String

    def function_index_url: () -> String

    def headline_init: () -> void

    def headline_push: () -> void

    def headline_pop: () -> void

    def headline: (String str, ?edit_url: String?) -> String

    def headline_noescape: (String str) -> String

    def search_form: () -> String

    def manual_home_name: () -> String

    def manual_home_link: () -> String

    def friendly_library_link: (String id) -> String

    def friendly_library_name: (String id) -> String

    def compile_method: (MethodEntry m, ?untyped? opt) -> String

    def compile_function: (FunctionEntry f, ?untyped? opt) -> String

    def compile_rd: (String src) -> String

    def rdcompiler: () -> RDCompiler

    def foreach_method_chunk: (String src) { (Array[MethodSignature], String) -> void } -> void

    def breadcrumb_json_ld: (Array[Hash[Symbol, String]] items) -> String

    def absolute_url_to: (String path) -> untyped
  end

  class IndexScreen < TemplateScreen
    @entries: Array[Entry]

    def initialize: (Hash[Symbol, untyped] h, Array[Entry] entries, Hash[Symbol, untyped] opt) -> void

    def encoding: () -> String

    alias charset encoding
  end

  class EntryBoundScreen < TemplateScreen
    @entry: untyped

    def initialize: (Hash[Symbol, untyped] h, Entry entry, Hash[Symbol, untyped] opt) -> void

    def encoding: () -> String

    alias charset encoding
  end

  class LibraryIndexScreen < IndexScreen
    def body: () -> String

    def current_url: () -> String
  end

  class LibraryScreen < EntryBoundScreen
    @entry: LibraryEntry

    def body: () -> String

    def draw_tree: (Array[ClassEntry] cs) { (?) -> untyped } -> void

    def current_url: () -> String

    private

    def draw_treed_entries: (Array[ClassEntry] entries, Hash[ClassEntry, Array[ClassEntry]] tree, ?Integer indent) { (ClassEntry, Integer) -> void } -> void
  end

  class ClassIndexScreen < IndexScreen
    def body: () -> String

    def current_url: () -> String
  end

  class OpenSearchDescriptionScreen < TemplateScreen
    def initialize: (Hash[Symbol, untyped] h, String request_full_uri, untyped opt) -> void

    attr_reader search_full_url: String

    def body: () -> String

    def content_type: () -> String
  end

  class SearchScreen < IndexScreen
    @query: String?

    @elapsed_time: Float

    def initialize: (Hash[Symbol, untyped] h, Array[Entry] entries, untyped opt) -> void

    def body: () -> String
  end

  class ClassScreen < EntryBoundScreen
    @entry: ClassEntry

    @alevel: Integer

    def initialize: (Hash[Symbol, untyped] h, ClassEntry entry, untyped opt) -> void

    def body: () -> String

    def current_url: () -> String
  end

  class MethodScreen < TemplateScreen
    @entries: Array[MethodEntry]

    def initialize: (Hash[Symbol, untyped] h, Array[MethodEntry] entries, untyped opt) -> void

    def encoding: () -> String

    alias charset encoding

    def body: () -> String

    def current_url: () -> String
  end

  class FunctionScreen < EntryBoundScreen
    @entry: FunctionEntry

    def body: () -> String

    def current_url: () -> String
  end

  class FunctionIndexScreen < IndexScreen
    def body: () -> String

    def current_url: () -> String
  end

  class DocScreen < EntryBoundScreen
    @entry: DocEntry

    def breadcrumb_title: () -> String

    def body: () -> String

    def rdcompiler: () -> RDCompiler

    def current_url: () -> String
  end
end
