module BitClust
  class Subcommand
    @parser: OptionParser

    # capi オプションが指定されたときだけ FunctionDatabase
    @db: FunctionDatabase | MethodDatabase

    def initialize: () -> void

    def parse: (Array[String] argv) -> void

    def help: () -> String

    def exec: (Array[String] argv, Hash[Symbol, untyped] options) -> void

    def error: (_ToS message) -> bot

    def option_error: (String message) -> bot

    def srcdir_root: () -> Pathname

    def align_progress_bar_title: (String title) -> String
  end
end
